### ISSUE TITLE
Out of memory when running the code

### ISSUE THREAD

**Issue by Flyingbeanss** [yunchengwang/GreenKGC#1]
Hi Yun-Cheng Wang!
I I am honored to read your paper “GreenKGC: A Lightweight Knowledge Graph Completion Method”.I am interested in your paper and I have run the open-source code directly used the default parameters provided by your paper.But when I run the code,it was killed and I found the code took up a lot of memory,closed to 350G.
May I know how to deal with it?
Thanks.

**Comment by HengYuh** [comment]
I meet this situation too,it shows like this "2023-09-03 14:24:25,286 INFO     === Current relation: 30 ===
Killed"

**Comment by Flyingbeanss** [comment]
Hi,@HengYuh.
Have you solved this  problem?

**Comment by bbbbbbxy** [comment]
@Flyingbeanss  have you solved the problem？I met with the same problem

**Comment by Flyingbeanss** [comment]
Hi, @bbbbbbxy. I haven't solved it yet.

**Comment by bbbbbbxy** [comment]
I wrote an eamail to the author,and  he told me it need 300G for traning ,maybe it's because of the memory and it exit with 137

**Comment by HengYuh** [comment]
got it ，thanks for your&nbsp; enthusiastic information！



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 16, 2023 12:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yunchengwang/GreenKGC] Out of memory when running the code(Issue #1)




 
I wrote an eamail to the author,and  he told me it need 300G for traning ,maybe it's because of the memory and it exit with 137

**Comment by Flyingbeanss** [comment]
Thanks @bbbbbbxy .
